server:
  port: 8437

spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/man?useSSL=true&&characterEncoding=utf8
    url: jdbc:mysql://127.0.0.1:3306/stock_project?useSSL=true&&characterEncoding=utf8&serverTimezone=UTC&&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  typeAliasesPackage: com.cqq.stock.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

stock-constant:
  day-stock-script-path: C:\Users\admin\PycharmProjects\stock_project\stock_data.py
  day-stock-exe-path: C:\Users\admin\PycharmProjects\stock_project\venv\Scripts\python.exe
  day-stock-dir: D:\\data\\stock\\day
  day-stock-path: D:\data\stock\day\{date}.txt
  day-stock-data-txt: D:\\data\\stock\\day\\{date}.txt
  result-dir: D:\newstock\{date}\result\
  logic-x-dir: D:\newstock\{date}\logicX\
