POST http://localhost:8437/stockForecasting/list
Content-Type: application/json

{
  "date": 20200108
}

###

POST http://localhost:8437/stockNew/rate
Content-Type: application/json

{
  "code": "sh501309",
  "date": 20200108
}

###

POST http://localhost:8437/macd/calculateMACD
Content-Type: application/json

{
  "code": "sz167302"
}

###
POST http://localhost:8437/sync/syncDataFromNetworkToDesk
Content-Type: application/json

{}

###
POST http://localhost:8437/sync/desk2DB
Content-Type: application/json

{}

###
POST http://localhost:8437/stockDayData/makeDataByCode
Content-Type: application/json

{
  "code":"sz002012"
}

###
POST http://localhost:8437/sync/dbCalculate
Content-Type: application/json

{}

###
POST http://localhost:8437/sync/changeError
Content-Type: application/json

{}

###
POST http://localhost:8437/sync/test
Content-Type: application/json

{}

###
POST http://localhost:8437/sync/syncDataFromNetworkToDeskQuickly
Content-Type: application/json

{}

###
